= Map File Descriptions
:revdate:   December 31, 2016
:revnumber: 1.0

Description of files used and generated alongside maps.

== Compiled files

[[mapname.bsp]]
_mapname_.bsp::
Binary Space Partition. The compiled and playable map file.

[[mapname.ext]]
_mapname_.ext::
Extent File. A file containing calculated face extents of the BSP. Used by RAD/LIGHT compiler to perform calculations. Not needed in distrobutions.

[[mapname.log]]
_mapname_.log::
Log File. Generated compile log file from the compiler processes. Not needed in distrobutions.

[[mapname.map]]
_mapname_.map::
Map File. Generated map file from the original Hammer or J.A.C.K. source file (.vmf, .jmf, .rmf). This map file is used by the CSG compiler. Not needed in distributions.

[[mapname.prt]]
_mapname_.prt::
Portal File. Generated by the BSP compiler and contains a list of portals in BSP file and used by VIS compiler to perform visibility calculations. Not needed in distrobutions.

[[mapname.wa_]]
_mapname_.wa_::
WAD File. A wad file containing included wad files (`-wadinclude`) within the compiled map. Used by RAD/LIGHT compiler to perform calculations. Not needed in distrobutions.

[[mapname.pts]]
Points File. Generated by the compiler tools and contains data about leaks in the map. Only generated if leaks were found during compilation.

[[mapname.lin]]
Linear Points File. Generated by the compiler tools and contains data about leaks in the map in a more linear fashion. Only generated if leaks were found during compilation. This is usually favoured over the points file as it is provides more linear lines, which makes them easier to track down.

== Text Files

[[mapname.txt]]
_mapname_.txt::
Map Description Text File. A file containing information about the map. This is no longer used, use <<mapname_motd.txt,`mapname_motd.txt`>> instead.

[[mapname_motd.txt]]
_mapname_motd_.txt::
Message of the Day Text File. A file containing information about the map. This content is shown at map start.

[[mapname_models.txt]]
_mapname_models_.txt::
Models Text File. A file containing a list of model paths and their replacement model paths.

[[mapname_detail.txt]]
_mapname_detail_.txt::
Detail Text File. A file containing a list of detail textures mapping. Used for overlaying detail images on existing textures within the map.

[[mapname_readme.txt]]
_mapname_readme_.txt::
Readme Text File. A file describing the map. Not used by Sven Co-Op.

[[mapname_credits.txt]]
_mapname_credits_.txt::
Credits Text File. A file describing credits for the map. Not used by Sven Co-Op.

[[mapname_materials.txt]]
_mapname_materials_.txt::
Materials Text File. A file containing a list of textures and their coresponding sound.

[[mapname_sentences.txt]]
_mapname_sentences_.txt::
Sentences Text File. A file containg a list of VOX sounds.

[[mapname.cfg]]
_mapname_.cfg::
Map Settings Configuration. A file for configuring map settings for the specific map. Overwrites settings in `default_map_settings.cfg`.

[[mapname_skl.cfg]]
_mapname_skl_.cfg::
Skill Configuration. A file describing skills for NPCs and monsters within the map.

[[mapname.res]]
_mapname_.res::
Resource File. A file containing a list of resources to be pre-loaded map load for client.

[[mapname.gmr]]
_mapname_.gmr::
Global Model Replacement. A file containing a list of model paths and their replacement model paths.

[[mapname.gsr]]
_mapname_.gsr::
Global Sound Replacement. A file containing a list of sound paths and their replacement sound paths.
