= Materials File Description
:revdate:   January 8, 2016
:revnumber: 1.1

When creating custom textures, you can define materials used within the map to give specific textures a sound style for when a player interacts (runs, attacks, etc.) with a brush/entity using that texture.

This can be done in multiple ways, such as prefixing texture names (Sven Co-Op only) or defining a `mapname_materials.txt` file.

== File Definition

The file contains a list of tags and their coressponding texture name.

```
V DUCT_FLR01
D GENERIC48
G CRETE2_FLR03
M AIR_C1
...
```

The letter describes the sound style to be used with the texture.

- `M` *metal* - Solid metal/steel sounds
- `V` *ventilation* - Resilient metal/brass sounds
- `D` *dirt* - Dry dirt/sand/gravel sounds
- `S` *slosh liquid* - Mud sounds
- `T` *tile* - Squeeky plastic tile sounds
- `G` *grate* - Reverbing metal grate sounds
- `W` *wood* - Wooden planks sounds
- `P` *computer* - Fragile metal/plastic/electronics sounds (hits only)
- `Y` *glass* - Glass sounds (hits only)
- `F` *flesh* - Flesh sounds; sort of like trampling through a muddy puddle
- `O` *snow* - Sound of crunching snow when walking over

Whereas _concrete_ is the default sound style. For example:

```
M MTL_FLOOR
T TILE_FLOOR
O MTN_SNOW01
```

=== Using Texture Names for Material Sounds

In Sven Co-Op, rather than creating a materials file, you can also name your textures with prefixes that will be used to determine their sound style.

```
V VENTTEXTURE_
D DIRTTEXTURE_
G GRATETEXTURE
M METALTEXTURE
S SLOSHTEXTURE
T TILETEXTURE_
W WOODTEXTURE_
P COMPTEXTURE_
Y GLASSTEXTURE
F FLESHTEXTURE
O SNOWTEXTURE_
```

So for example, if you have a texture `MTL_FLOOR` you can rename it to `METALTEXTUREMTL_FLOOR`, or `SNOWTEXTURE_MTN_SNOW01`.

[NOTE]
====
The maximum name of a texture is 15 characters.
====

== Custom Materials File

To use custom material sounds for textures, without using texture names a custom materials file can be used.

Create a `materials.txt` file in `sound/<mapname>`. Add materials, as described above.

[NOTE]
====
You can choose any name and location for the sentences file, but it is highly recommended to call it `materials.txt` and locate it in `svencoop_addon/sound/<mapname>/materials.txt`.
====

To use your custom materials file you can either:

a. Change `materials_file` keyvalue in the `worldspawn` entity of your map (Map Properties).
b. Create a config file `<mapname>.cfg` and set the `materials_file` cvar to the path of your sentence file.

```
materials_file sound/mymap/materials.txt
```

[IMPORTANT]
====
Setting `materials_file` keyvalue in `worldspawn` doesn't seem to work properly. To be on the safe side, use the configuration file instead.
====

[IMPORTANT]
====
Use the `svencoop_addon` directory for all custom content, to avoid changing original game content.
====

== See Also

- link:https://sites.google.com/site/svenmanor/material-sounds[Sven Manor Entity Guide: Material Sounds]
